name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente o workflow via GUI do Github

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VAR_T1: t1
      VAR_T2: t2
    steps:
    - uses: actions/checkout@v4

    - name: GO 1.22 setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Go Project
      run: go build -o main go_files/main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: programa_go_main
        path: main

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
